web:
  image: nginx:1.21.6
  ports:
    - "8080:80"
    - "443:443"
  volumes:
    - ./app:/app
    - ./site.conf:/etc/nginx/conf.d/default.conf
    - ./ssl/:/etc/nginx/certs
  links:
    - app

app:
#  image: php:7-fpm
  build: .
  expose: 
    - 9000
  volumes:
    - ./app:/app
    - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - ./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini